eShopCoreWeb.AdminApp/Controllers/CategoryController.cs
using eShopCoreWeb.ApiIntegration;
using eShopCoreWeb.ViewModels.Catalog.Categories;
using eShopCoreWeb.ViewModels.Catalog.Products;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace eShopCoreWeb.AdminApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryApiClient _categoryApiClient;
        private readonly IConfiguration _configuration;
        public CategoryController(IConfiguration configuration, ICategoryApiClient categoryApiClient)
        {
            _configuration = configuration;
            _categoryApiClient = categoryApiClient;
        }
        [HttpGet]
        public async Task<IActionResult> Index(string languageId = "vi")
        {
            // Lấy token từ Session
            var sessions = HttpContext.Session.GetString("Token");


            // Gọi API để lấy danh sách danh muc
            var categories = await _categoryApiClient.GetAll(languageId);
            foreach(var category in categories)
            {
                category.BearerToken = sessions;
            }
            if (categories == null)
                return BadRequest("Không tìm được");
            ViewBag.ResultMsg = TempData["result"];
            return View(categories);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] CategoryCreateRequest request)
        {

            if (!ModelState.IsValid)
                return View();
            // Gọi API để tạo sản phẩm
            var result = await _categoryApiClient.CreateCategory(request);
            if (result)
            {
                TempData["result"] = "Thêm danh mục thành công";
                return RedirectToAction("Index");
            }
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id, string languageId = "vi")
        {
            // Gọi API để lấy thông tin danh muc theo ID và ngôn ngữ
            var category = await _categoryApiClient.GetCategoryById(id, languageId);
            if (category != null)
            {
                var updateRequest = new CategoryUpdateRequest()
                {
                    SeoAlias = category.SeoAlias,
                    Name = category.Name,
                    SeoDescription = category.SeoDescription,
                    SeoTitle = category.SeoTitle,
                    LanguageId = languageId,
                    Id = category.Id,
                    IsShowOnHome = category.IsShowOnHome,
                    ParentId = category.ParentId,
                    SortOrder =category.SortOrder,
                    Status = category.Status,
                };
                return View(updateRequest);
            }
            return RedirectToAction("Error", "Home");
        }
        // Xử lý việc cập nhật danh muc khi submit form chỉnh sửa =
        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] CategoryUpdateRequest request)
        {

            if (!ModelState.IsValid)
                return View();
            // Gọi API để cập nhật danh muc
            var result = await _categoryApiClient.UpdateCategory(request);
            if (result)
            {
                TempData["result"] = "Cập nhật danh muc thành công";
                return RedirectToAction("Index");
            }
            return View(request);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            // Gọi API để lấy thông tin sản phẩm theo ID và ngôn ngữ
            var result = await _categoryApiClient.DeleteCategory(id);
            if (result)
            {
                TempData["result"] = "Xóa danh muc thành công";
            }
            else
            {
                TempData["result"] = "Xóa danh muc  thất bại";
            }
            return RedirectToAction("Index");
        }

    }
}

eShopCoreWeb.AdminApp/Controllers/ProductController.cs
using eShopCoreWeb.ApiIntegration;
using eShopCoreWeb.ViewModels.Catalog.ProductImages;
using eShopCoreWeb.ViewModels.Catalog.Products;
using eShopCoreWeb.ViewModels.Common;
using eShopCoreWeb.ViewModels.System.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Build.Globbing;

namespace eShopCoreWeb.AdminApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductApiClient _productApiClient;
        private readonly ICategoryApiClient _categoryApiClient;
        private readonly IConfiguration _configuration;
        public ProductController(IProductApiClient productApiClient, IConfiguration configuration, ICategoryApiClient categoryApiClient)
        {
            _productApiClient = productApiClient;
            _configuration = configuration;
            _categoryApiClient = categoryApiClient;
        }
        [HttpGet]
        public async Task<IActionResult> Index(int? categoryId,string keyword = "default", int pageIndex = 1, int pageSize = 2, string languageId="vi")
        {
            // Lấy token từ Session
            var sessions = HttpContext.Session.GetString("Token");

            // Tạo request để lấy danh sách sản phẩm theo trang và từ khóa tìm kiếm
            var request = new GetManageProductPagingRequest()
            {
                BearerToken = sessions,
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize,
                LanguageId = languageId,
                CategoryId = categoryId
            };

            // Gọi API để lấy danh sách sản phẩm
            var data = await _productApiClient.GetProductPaging(request);
            var categories = await _categoryApiClient.GetAll(languageId);
            ViewBag.Categories = categories.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
                Selected = categoryId.HasValue && categoryId.Value == x.Id
            });
            if (data == null)
                return BadRequest("Không tìm được");
            ViewBag.ResultMsg = TempData["result"];
            return View(data);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create([FromForm] ProductCreateRequest request)
        {

            if (!ModelState.IsValid)
                return View();
            // Gọi API để tạo sản phẩm
            var result = await _productApiClient.CreateProduct(request);
            if (result)
            {
                TempData["result"] = "Thêm sản phẩm thành công";
                return RedirectToAction("Index");
            }
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id, string languageId="vi")
        {
            // Gọi API để lấy thông tin sản phẩm theo ID và ngôn ngữ
            var product = await _productApiClient.GetProductById(id, languageId);
            var listImage = await _productApiClient.GetListImage(id);
            if (product!= null)
            {
                var updateRequest = new ProductUpdateRequest()
                {
                    SeoAlias = product.SeoAlias,
                    Description = product.Description,
                    Details = product.Details,
                    Name = product.Name,
                    SeoDescription = product.SeoDescription,
                    SeoTitle = product.SeoTitle,
                    LanguageId = languageId,
                    Id = id,
                };
                if(listImage!=null)
                    ViewBag.Image = listImage.FirstOrDefault().ImagePath;
                return View(updateRequest);
            }
            return RedirectToAction("Error", "Home");
        }
        // Xử lý việc cập nhật sản phẩm khi submit form chỉnh sửa bao gồm file ảnh
        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Edit([FromForm] ProductUpdateRequest request)
        {

            if (!ModelState.IsValid)
                return View();
            // Gọi API để cập nhật sản phẩm
            var result = await _productApiClient.UpdateProduct(request);
            if (result)
            {
                TempData["result"] = "Cập nhật sản phẩm thành công";
                return RedirectToAction("Index");
            }
            return View(request);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateFeature(int productId)
        {
            var product = await _productApiClient.GetProductById(productId, "vi");
            bool isFeatured;
            if (product.IsFeatured==true)
            {
                isFeatured=false;   
            }
            else
            {
                isFeatured = true;
            }    
            var result = await _productApiClient.UpdateFeature(productId, isFeatured);
            if (result)
            {
                TempData["result"] = $"Cập nhật feature của {product.Name} thành {isFeatured} thành công";
            }
            else
            {
                TempData["result"] = $"Cập nhật status của {product.Name}  thành {isFeatured} thất bại";
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateStock(int productId, int addedQuantity)
        {
            var product = await _productApiClient.GetProductById(productId, "vi");
            var result = await _productApiClient.UpdateStock(productId, addedQuantity);
            if (result)
            {
                TempData["result"] = $"Cập nhật số lượng của {product.Name} thành công";
            }
            else
            {
                TempData["result"] = $"Cập nhật số lượng của {product.Name} thất bại";
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> UpdatePrice(int productId, decimal newPrice)
        {
            var product = await _productApiClient.GetProductById(productId, "vi");
            var result = await _productApiClient.UpdatePrice(productId, newPrice);
            if (result)
            {
                TempData["result"] = $"Cập nhật giá của {product.Name} thành công";
            }
            else
            {
                TempData["result"] = $"Cập nhật giá của {product.Name} thất bại";
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id, string languageId)
        {
            // Gọi API để lấy thông tin sản phẩm theo ID và ngôn ngữ
            var product = await _productApiClient.GetProductById(id, languageId);
            return View(product);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            // Gọi API để xóa sản phẩm theo Id
            var result = await _productApiClient.DeleteProduct(id);
            if (result)
            {
                TempData["result"] = "Xóa sản phẩm thành công";
            }
            else
            {
                TempData["result"] = "Xóa sản phẩm thất bại";
            }
            return RedirectToAction("Index");
        }

        [HttpGet("cap-nhat-danh-muc")]
        public async Task<IActionResult> CategoryAssign(int id,string languageId)
        {
            var roleAssignRequsest = await GetCategoryAssignRequest(id, languageId);
            return View(roleAssignRequsest);
        }

        [HttpPost("cap-nhat-danh-muc")]
        public async Task<IActionResult> CategoryAssign(CategoryAssignRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _productApiClient.CategoryAssign(request.Id, request);

            if (result.IsSuccessed)
            {
                TempData["result"] = "Cập nhật danh mục thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            var categoryAssignRequest = await GetCategoryAssignRequest(request.Id, "vi");

            return View(categoryAssignRequest);
        }
        public async Task<CategoryAssignRequest> GetCategoryAssignRequest(int id, string languageId)
        {
            var product = await _productApiClient.GetProductById(id, languageId);
            var categories = await _categoryApiClient.GetAll(languageId);
            categories = categories.FindAll(x=>x.ParentId==0);
            var categoryAssignRequest = new CategoryAssignRequest();
            categoryAssignRequest.Id = product.Id;
            foreach (var category in categories)
            {
                categoryAssignRequest.Categories.Add(new SelectItem()
                {
                    Id = category.Id.ToString(),
                    Name = category.Name,
                    
                    Selected = product.Categories.Contains(category.Name)
                });
            }
            return categoryAssignRequest;
        }

        [HttpGet]
        public async Task<IActionResult> AddImages(int productId)
        {
            var productImages = await _productApiClient.GetListImage(productId);
            ViewBag.ProductId = productId;
            if (productImages != null)
                ViewBag.Images = productImages;
            ViewBag.ResultMsg = TempData["result"];
            return View();
        }
        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> AddImages(int productId, ProductImageCreateRequest request)
        {

            if (!ModelState.IsValid)
                return View();

eShopCoreWeb.AdminApp/Views/Category/Create.cshtml
@model eShopCoreWeb.ViewModels.Catalog.Categories.CategoryCreateRequest

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h1>Tạo mới danh mục</h1>
    <!-- DataTales Example -->
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
        <li class="breadcrumb-item active">Tạo mới danh mục</li>
    </ol>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"><a class="btn btn-success" asp-controller="Category" asp-action="Index">Danh sách </a></h6>
        </div>
        <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="SortOrder" class="control-label"></label>
                        <input asp-for="SortOrder" class="form-control" />
                        <span asp-validation-for="SortOrder" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="IsShowOnHome" /> @Html.DisplayNameFor(model => model.IsShowOnHome)
                        </label>
                    </div>
                    <div class="form-group">
                        <label asp-for="ParentId" class="control-label"></label>
                        <input asp-for="ParentId" class="form-control" />
                        <span asp-validation-for="ParentId" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Status" /> @Html.DisplayNameFor(model => model.Status)
                        </label>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SeoDescription" class="control-label"></label>
                        <input asp-for="SeoDescription" class="form-control" />
                        <span asp-validation-for="SeoDescription" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SeoTitle" class="control-label"></label>
                        <input asp-for="SeoTitle" class="form-control" />
                        <span asp-validation-for="SeoTitle" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LanguageId" class="control-label"></label>
                        <input asp-for="LanguageId" class="form-control" />
                        <span asp-validation-for="LanguageId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SeoAlias" class="control-label"></label>
                        <input asp-for="SeoAlias" class="form-control" />
                        <span asp-validation-for="SeoAlias" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        </div>
    </div>
</div>

eShopCoreWeb.AdminApp/Views/Category/Edit.cshtml
@model eShopCoreWeb.ViewModels.Catalog.Categories.CategoryUpdateRequest

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h1>Cập nhật danh mục</h1>
    <!-- DataTales Example -->
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
        <li class="breadcrumb-item active">Cập nhật danh mục</li>
    </ol>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"><a class="btn btn-success" asp-controller="Product" asp-action="Index">Danh sách </a></h6>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Id" class="control-label"></label>
                            <input asp-for="Id" class="form-control" />
                            <span asp-validation-for="Id" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SortOrder" class="control-label"></label>
                            <input asp-for="SortOrder" class="form-control" />
                            <span asp-validation-for="SortOrder" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="IsShowOnHome" class="control-label"></label>
                            <input asp-for="IsShowOnHome" class="form-control" />
                            <span asp-validation-for="IsShowOnHome" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ParentId" class="control-label"></label>
                            <input asp-for="ParentId" class="form-control" />
                            <span asp-validation-for="ParentId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Status" class="control-label"></label>
                            <input asp-for="Status" class="form-control" />
                            <span asp-validation-for="Status" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SeoDescription" class="control-label"></label>
                            <input asp-for="SeoDescription" class="form-control" />
                            <span asp-validation-for="SeoDescription" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SeoTitle" class="control-label"></label>
                            <input asp-for="SeoTitle" class="form-control" />
                            <span asp-validation-for="SeoTitle" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="LanguageId" class="control-label"></label>
                            <input asp-for="LanguageId" class="form-control" />
                            <span asp-validation-for="LanguageId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SeoAlias" class="control-label"></label>
                            <input asp-for="SeoAlias" class="form-control" />
                            <span asp-validation-for="SeoAlias" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>

eShopCoreWeb.AdminApp/Views/Category/Index.cshtml
@model IEnumerable<eShopCoreWeb.ViewModels.Catalog.Categories.CategoryViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts{
    <script>
        setTimeout(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);
    </script>
}
    <div class="container-fluid">
        <h1>Danh sách danh mục</h1>
        <!-- DataTales Example -->
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
            <li class="breadcrumb-item active">Danh sách  danh mục</li>
        </ol>
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary"><a class="btn btn-success" asp-controller="Category" asp-action="Create">Tạo mới danh mục </a></h6>
                <p></p>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                    @if (ViewBag.ResultMsg != null && ViewBag.ResultMsg.Contains("thành công"))
                    {
                        <div class="alert alert-success" role="alert">
                            @ViewBag.ResultMsg
                        </div>
                    }
                    @if (ViewBag.ResultMsg != null && ViewBag.ResultMsg.Contains("thất bại"))
                    {
                        <div class="alert alert-danger" role="alert">
                            @ViewBag.ResultMsg
                        </div>
                    }
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Id)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SortOrder)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.IsShowOnHome)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ParentId)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Status)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SeoDescription)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SeoTitle)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LanguageId)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SeoAlias)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.BearerToken)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SortOrder)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IsShowOnHome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ParentId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Status)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SeoDescription)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SeoTitle)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LanguageId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SeoAlias)
                                </td>
                                <td>
                                    @Html.ActionLink("Sửa", "Edit", "Category", new {  id=item.Id  }) |
                                    @Html.ActionLink("Các sản phẩm", "Index","Product", new {categoryId =item.Id }) |
                                    @Html.ActionLink("Xóa", "Delete","Category", new { id=item.Id  })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
<!-- End of Main Content -->