eShopCoreWeb/Models/CheckoutViewModel.cs
using eShopCoreWeb.ViewModels.Sales;

namespace eShopCoreWeb.WebApp.Models
{
    public class CheckoutViewModel
    {
        public List<CartItemViewModel> CartItems { get; set; }

        public CheckoutRequest CheckoutModel { get; set; }
    }
}

eShopCoreWeb/Controllers/CartController.cs
using eShopCoreWeb.ApiIntegration;
using eShopCoreWeb.Utilities.Constants;
using eShopCoreWeb.ViewModels.Sales;
using eShopCoreWeb.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;

namespace eShopCoreWeb.WebApp.Controllers
{
    public class CartController:Controller
    {
        private readonly IUserApiClient _userApiClient;
        private readonly IProductApiClient _productApiClient;
        private readonly IOrderApiClient _orderApiClient;
        public CartController(IProductApiClient productApiClient, IOrderApiClient orderApiClient, IUserApiClient userApiClient)
        {
            _productApiClient = productApiClient;
            _orderApiClient = orderApiClient;
            _userApiClient = userApiClient;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Checkout()
        {
            return View(GetCheckoutViewModel());
        }
        [HttpPost]
        public async Task<IActionResult> Checkout(CheckoutViewModel request)
        {
            var userName = User.Identity.Name;
            var userEmail = User.FindFirstValue(ClaimTypes.Email);
            var userObj = await _userApiClient.GetUserByUserName(userName);
            if(userObj==null)
            {
                userObj = await _userApiClient.GetUserByEmail(userEmail);
            }
            var model = GetCheckoutViewModel();
            var orderDetails = new List<OrderDetailViewModel>();
            foreach (var item in model.CartItems)
            {
                orderDetails.Add(new OrderDetailViewModel()
                {
                    ProductId = item.ProductId,
                    Quantity = item.Quantity,
                    Price = item.Price,
                });
            }
            var checkoutRequest = new CheckoutRequest()
            {
                Address = request.CheckoutModel.Address,
                Name = request.CheckoutModel.Name,
                Email = request.CheckoutModel.Email,
                PhoneNumber = request.CheckoutModel.PhoneNumber,
                OrderDetails = orderDetails
            };
            var result = await _orderApiClient.CreateOrder(userObj.ResultObj.Id, checkoutRequest);
            if (result)
            {
                TempData["SuccessMsg"] = "Order puschased successful";
                return View(model);
            }
            TempData["SuccessMsg"] = "Order puschased fail";
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> GetListCartItem()
        {
            var order = await _orderApiClient.GetOrderById(3);
            var session = HttpContext.Session.GetString(SystemConstants.CartSession);
            List<CartItemViewModel> currentCart = new List<CartItemViewModel>();
            if (session != null)
                currentCart = JsonConvert.DeserializeObject<List<CartItemViewModel>>(session);
            return Ok(currentCart);
        }
        public async Task<IActionResult> AddToCart(int id, string languageId, int cartQuantity)
        {
            //if (!User.Identity.IsAuthenticated)
            //{
            //    // Lưu đường dẫn hiện tại vào TempData với tên "ReturnUrl"
            //    TempData["ReturnUrl"] = Url.Action("AddToCart", "Cart", new { Id = id, languageId = languageId });

            //    // Redirect đến trang đăng nhập
            //    return RedirectToAction("Index", "Account");
            //}
            var product = await _productApiClient.GetProductById(id, languageId);
            var session = HttpContext.Session.GetString(SystemConstants.CartSession);
            List<CartItemViewModel> currentCart = new List<CartItemViewModel>();
            if (session != null)
                currentCart = JsonConvert.DeserializeObject<List<CartItemViewModel>>(session);  
            int quantity;
            if(cartQuantity!=null || cartQuantity>0)
            {
                quantity = cartQuantity;
            }
            else
            {
                quantity = 1;
            }
            if (currentCart.Any(x => x.ProductId == id))
            {
                currentCart.First(x => x.ProductId == id).Quantity += quantity; 
                HttpContext.Session.SetString(SystemConstants.CartSession, JsonConvert.SerializeObject(currentCart));
                return Ok(currentCart);
            }

            var cartItem = new CartItemViewModel()
            {
                ProductId = id,
                Description = product.Description,
                Image = product.ThumnailImage,
                Name = product.Name,
                Price = product.Price,
                Quantity = quantity,
                UserName = User.Identity.Name,
            };

            currentCart.Add(cartItem);

            HttpContext.Session.SetString(SystemConstants.CartSession, JsonConvert.SerializeObject(currentCart));
            return Ok(currentCart);
        }

        public  IActionResult UpdateCart(int id, int quantity)
        {
            var session = HttpContext.Session.GetString(SystemConstants.CartSession);
            List<CartItemViewModel> currentCart = new List<CartItemViewModel>();
            if (session != null)
                currentCart = JsonConvert.DeserializeObject<List<CartItemViewModel>>(session);
            foreach(var item in currentCart)
            {
                if (item.ProductId == id)
                {
                    if (quantity == 0)
                    {
                        currentCart.Remove(item);
                        break;
                    }    
                    item.Quantity = quantity;
                };
            }    
            HttpContext.Session.SetString(SystemConstants.CartSession, JsonConvert.SerializeObject(currentCart));
            return Ok(currentCart);
        }
        private CheckoutViewModel GetCheckoutViewModel()
        {
            var session = HttpContext.Session.GetString(SystemConstants.CartSession);
            List<CartItemViewModel> currentCart = new List<CartItemViewModel>();
            if (session != null)
                currentCart = JsonConvert.DeserializeObject<List<CartItemViewModel>>(session);
            var checkoutVm = new CheckoutViewModel()
            {
                CartItems = currentCart,
                CheckoutModel = new CheckoutRequest()
            };
            return checkoutVm;
        }
    }
}

eShopCoreWeb/Controllers/ProductController.cs
using eShopCoreWeb.Application.Catalog.Products;
using eShopCoreWeb.Data.EF;
using eShopCoreWeb.Data.Entities;
using eShopCoreWeb.ViewModels.Catalog.Products;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using static Microsoft.Extensions.Logging.EventSource.LoggingEventSource;
using System.Drawing.Printing;
using eShopCoreWeb.ApiIntegration;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.RegularExpressions;

namespace eShopCoreWeb.WebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductApiClient _productApiClient;
        private readonly ICategoryApiClient _categoryApiClient;
        private readonly IConfiguration _configuration;
        public ProductController(IProductApiClient productApiClient, IConfiguration configuration, ICategoryApiClient categoryApiClient)
        {
            _productApiClient = productApiClient;
            _configuration = configuration;
            _categoryApiClient = categoryApiClient;
        }
        [HttpGet]
        // GET: ProductsController
        public async Task<IActionResult> Index(int? categoryId, int? sort, string keyword = "default", int pageIndex = 1, int pageSize = 2, string culture = "vi")
        {


            // Lấy token từ Session
            var sessions = HttpContext.Session.GetString("Token");

            // Tạo request để lấy danh sách sản phẩm theo trang và từ khóa tìm kiếm
            var request = new GetManageProductPagingRequest()
            {
                BearerToken = sessions,
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize,
                LanguageId = culture,
                CategoryId = categoryId,
                Sort =sort
            };

            // Gọi API để lấy danh sách sản phẩm
            var data = await _productApiClient.GetProductPaging(request);
            var categories = await _categoryApiClient.GetAll(culture);
            ViewBag.Categories = categories.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
                Selected = categoryId.HasValue && categoryId.Value == x.Id
            });
            if (data == null)
                return BadRequest("Không tìm được");
            ViewBag.ResultMsg = TempData["result"];
            return View(data);
        }

        // GET: ProductsController/Details/5
        public async Task<IActionResult> Detail(int id, string culture)
        {
            var product = await _productApiClient.GetProductById(id, culture);
            var productImages = await _productApiClient.GetListImage(id);
            return View(new WebApp.Models.ProductDetailViewModel()
            {
                Product = product,
                ProductImages = productImages
            });
        }

        // GET: ProductsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProductsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProductsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

eShopCoreWeb/Views/Cart/Checkout.cshtml
@model CheckoutViewModel
@{
    ViewData["Title"] = "Checkout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration;
@{
    var culture = CultureInfo.CurrentCulture.Name;
}
<ul class="breadcrumb">
    <li><a href="@Url.Action("Index", "Home", new {culture=culture})"><localize>Home</localize></a> <span class="divider">/</span></li>
    <li class="active"> <localize>SHOPPING CART</localize></li>
</ul>
<h3>
   
    <localize> SHOPPING CART</localize>[ <small>@Model.CartItems.Count Item(s) </small>]
    <a href="@Url.Action("Index", "Product", new {culture=culture})" class="btn btn-large pull-right"><i class="icon-arrow-left"></i><localize> Continue Shopping</localize> </a>
</h3>
<hr class="soft" />
@if (TempData["SuccessMsg"] != null)
{
    <span class="alert alert-success"><localize>@TempData["SuccessMsg"]</localize></span>
    <h3 localize-content>Order Item List</h3>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th localize-content>Product</th>
                <th localize-content>Description</th>
                <th localize-content>Quantity</th>
                <th localize-content>Price</th>
                <th localize-content>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.CartItems)
            {
                <tr>
                    <td> <img width="60" src="@(Configuration["BaseAddress"]+"/user-content/" + item.Image)" alt="" /></td>
                    <td>@item.Description</td>
                    <td>
                        @item.Quantity
                    </td>
                    <td>@item.Price</td>
                    <td>@(item.Quantity * item.Price)</td>
                </tr>
            }

            <tr>
                <td colspan="4" style="text-align:right"><strong>TOTAL =</strong></td>
                <td class="label label-important" style="display:block"> <strong> @Model.CartItems.Sum(x => x.Quantity * x.Price).ToString("N0")</strong></td>
            </tr>
        </tbody>
    </table>
}
else
{

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Product</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.CartItems)
            {
                <tr>
                    <td> <img width="60" src="@(Configuration["BaseAddress"]+"/user-content/" + item.Image)" alt="" /></td>
                    <td>@item.Description</td>
                    <td>
                        @item.Quantity
                    </td>
                    <td>@item.Price</td>
                    <td>@(item.Quantity*item.Price)</td>
                </tr>
            }

            <tr>
                <td colspan="4" style="text-align:right"><strong>TOTAL =</strong></td>
                <td class="label label-important" style="display:block"> <strong> @Model.CartItems.Sum(x => x.Quantity * x.Price).ToString("N0")</strong></td>
            </tr>
        </tbody>
    </table>

    <table class="table table-bordered">
        <tr><th>ESTIMATE YOUR SHIPPING </th></tr>
        <tr>
            <td>
                <form class="form-horizontal" asp-action="Checkout" asp-controller="Cart" method="post">
                    <div class="control-group">
                        <label class="control-label" for="inputCountry">Name </label>
                        <div class="controls">
                            <input type="text" id="inputCountry" asp-for="CheckoutModel.Name" placeholder="Name">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="inputCountry">Address </label>
                        <div class="controls">
                            <input type="text" id="inputCountry" asp-for="CheckoutModel.Address" placeholder="Address">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="inputCountry">Email </label>
                        <div class="controls">
                            <input type="text" id="inputCountry" asp-for="CheckoutModel.Email" placeholder="Email">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="inputCountry">PhoneNumber </label>
                        <div class="controls">
                            <input type="text" id="inputCountry" asp-for="CheckoutModel.PhoneNumber" placeholder="PhoneNumber">
                        </div>
                    </div>

                    <div class="control-group">
                        <div class="controls">
                            <button type="submit" class="btn">Purchase </button>
                        </div>
                    </div>
                </form>
            </td>
        </tr>
    </table>
    <a href="/" class="btn btn-large"><i class="icon-arrow-left"></i> Continue Shopping </a>
}

eShopCoreWeb/Views/Cart/Index.cshtml
﻿@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
    <script src="~/js/cart2.js"></script>
    <script>
        var cartController = new CartController();
        cartController.initialize();
    </script>
}

    <ul class="breadcrumb">
        <li><a href="index.html">Home</a> <span class="divider">/</span></li>
        <li class="active"> SHOPPING CART</li>
    </ul>

    <h3>
        SHOPPING CART [ <small><span id="lbl_number_of_items">0</span> Item(s) </small>]
        <a href="products.html" class="btn btn-large pull-right"><i class="icon-arrow-left"></i> Continue Shopping </a>
    </h3>

    <hr class="soft" />

    <table class="table table-bordered" id="tbl_cart">
        <thead>
            <tr>
                <th>Product</th>
                <th>Description</th>
                <th>Quantity/Update</th>
                <th>Price</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody id="cart_body">
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" style="text-align:right"><strong>TOTAL =</strong></td>
                <td class="label label-important" style="display:block"> <strong> <span id="lbl_total"></span> </strong></td>
            </tr>
        </tfoot>
    </table>

    <a href="@Url.Action("Index","Product", new {languageId="vi"})" class="btn btn-large"><i class="icon-arrow-left"></i> Continue Shopping </a>
    <a href="@Url.Action("Checkout","Cart")" class="btn btn-large pull-right">Next <i class="icon-arrow-right"></i></a>