eShopCoreWeb.AdminApp/Controllers/Components/PagerViewComponent.cs
using eShopCoreWeb.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;

namespace eShopCoreWeb.AdminApp.Controllers.Components
{
    public class PagerViewComponent:ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

eShopCoreWeb.AdminApp/Controllers/OrderController.cs
using eShopCoreWeb.ApiIntegration;
using eShopCoreWeb.ViewModels.Sales;
using eShopCoreWeb.ViewModels.System.Users;
using Microsoft.AspNetCore.Mvc;

namespace eShopCoreWeb.AdminApp.Controllers
{
    public class OrderController : Controller
    {
        private IOrderApiClient _orderApiClient;
        public OrderController(IOrderApiClient orderApiClient)
        {
            _orderApiClient = orderApiClient;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Index(string keyword = "default", int pageIndex = 1, int pageSize = 2)
        {
            var sessions = HttpContext.Session.GetString("Token");

            var request = new GetOrderPagingRequest()
            {
                BearerToken = sessions,
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _orderApiClient.GetOrderPaging(request);
            if (data == null)
                return BadRequest("Khong tim duoc");
            ViewBag.ResultMsg = TempData["result"];
            return View(data.ResultObj);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateStatus(int orderId, int status)
        {
            // Gọi API để cập nhật trạng thái đơn hàng
            var order = _orderApiClient.GetOrderById(orderId);  
            var result = await _orderApiClient.UpdateStatus(orderId, status);
            if (result)
            {
                TempData["result"] = $"Cập nhật status của {order.Result.ShipName} thành công";
            }
            else
            {
                TempData["result"] = $"Cập nhật status của {order.Result.ShipName} thất bại";
            }
            return RedirectToAction("Index");
        }
    }
}

eShopCoreWeb.AdminApp/Controllers/UsersController.cs
using eShopCoreWeb.ViewModels.System.Users;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;
using NuGet.Protocol;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using eShopCoreWeb.ViewModels.Common;
using eShopCoreWeb.ApiIntegration;

namespace eShopCoreWeb.AdminApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class UsersController : Controller
    {
        private readonly IUserApiClient _userApiClient;
        private readonly IRoleApiClient _roleApiClient;
        private readonly IConfiguration _configuration;
        [AllowAnonymous]
        public IActionResult Forbidden()
        {
            return View();
        }
        public UsersController(IUserApiClient userApiClient, IRoleApiClient roleApiClient, IConfiguration configuration)
        { 
            _userApiClient = userApiClient;
            _configuration = configuration;
            _roleApiClient = roleApiClient;
        }
        [HttpGet("danh-sach-nguoi-dung")]
        public async Task<IActionResult> Index(string keyword="default", int pageIndex = 1, int pageSize = 2)
        {
            var sessions = HttpContext.Session.GetString("Token");

            var request = new GetUserPagingRequest()
            {
                BearerToken = sessions,
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _userApiClient.GetUserPaging(request);
            if (data == null)
                return BadRequest("Khong tim duoc");
            ViewBag.ResultMsg = TempData["result"];
            return View(data.ResultObj);
        }
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var user = await _userApiClient.GetUserById(id);
            return View(user.ResultObj);
        }
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Login");
        }
        
        [HttpGet("tao-nguoi-dung")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost("tao-nguoi-dung")]
        public async Task<IActionResult> Create(RegisterRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _userApiClient.Register(request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Thêm người dùng thành công";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", result.Message);
            return View(request);
        }
        [HttpGet("cap-nhat")]
        public async Task<IActionResult> Update(Guid id)
        {
            var result = await _userApiClient.GetUserById(id);
            if (result.IsSuccessed)
            {
                var user = result.ResultObj;
                var updateRequest = new UserUpdateRequest()
                {
                    Dob = user.Dob,
                    Email = user.Email,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    PhoneNumber = user.PhoneNumber,
                    Id = id
                };
                return View(updateRequest);
            }
            return RedirectToAction("Error", "Home");
        }

        [HttpPost("cap-nhat")]
        public async Task<IActionResult> Update(UserUpdateRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _userApiClient.Update(request.Id, request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Cập nhật người dùng thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            return View(request);
        }

        [HttpGet("xoa-nguoi-dung/{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _userApiClient.Delete(id);
            if(result.IsSuccessed)
            {
                TempData["result"] = "Xóa người dùng thành công";
                return RedirectToAction("Index");
            }
            TempData["result"] = "Xóa người dùng không thành công";
            return RedirectToAction("Index");

        }
        [HttpGet("cap-nhat-role")]
        public async Task<IActionResult> RoleAssign(Guid id)
        {
            var roleAssignRequsest = await GetRoleAssignRequest(id);
            return View(roleAssignRequsest);
        }

        [HttpPost("cap-nhat-role")]
        public async Task<IActionResult> RoleAssign(RoleAssignRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _userApiClient.RoleAssign(request.RoleId, request);

            if (result.IsSuccessed)
            {
                TempData["result"] = "Cập nhật quyền thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            var roleAssignRequest = await GetRoleAssignRequest(request.RoleId);

            return View(roleAssignRequest);
        }
        public async Task<RoleAssignRequest> GetRoleAssignRequest(Guid id)
        {
            var userObj = await _userApiClient.GetUserById(id);
            var roleObj = await _roleApiClient.GetAll();
            var roleAssignRequest = new RoleAssignRequest();
            roleAssignRequest.RoleId = userObj.ResultObj.Id;
            foreach (var role in roleObj.ResultObj)
            {
                roleAssignRequest.Roles.Add(new SelectItem()
                {
                    Id = role.Id.ToString(),
                    Name = role.Name,
                    Selected = userObj.ResultObj.Roles.Contains(role.Name)
                });
            }
            return roleAssignRequest;
        }
    }
}

eShopCoreWeb.AdminApp/Views/Order/Index.cshtml
@using eShopCoreWeb.ViewModels.Common;
@model PagedResult<eShopCoreWeb.ViewModels.Sales.OrderViewModel>

@{
	ViewData["Title"] = "Danh sách don hang";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
	<script>
		setTimeout(function () {
			$('#msgAlert').fadeOut('slow');
		}, 2000);
	</script>
}
	<div class="container-fluid">
		<h1>Danh sách don hang</h1>
		<!-- DataTales Example -->
		<ol class="breadcrumb mb-4">
			<li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
			<li class="breadcrumb-item active">Danh sách don hang</li>
		</ol>
		<!-- DataTales Example -->
		<div class="card shadow mb-4">
			<div class="card-header py-3">
				<h6 class="m-0 font-weight-bold text-primary"><a class="btn btn-success" asp-controller="Users" asp-action="Create">Tạo mới người dùng </a></h6>
				<form asp-action="Index" method="get" class="d-none d-sm-inline-block form-inline mr-auto mw-100 navbar-search">
					<input type="text" name="keyword" class="form-control" />
					<button class="btn btn-primary" type="submit"><i class="fas fa-search fa-sm"></i> Tìm kiếm</button>
				</form>
			</div>
			<div class="card-body">
				<div class="row">
					<div class="col-md-6">
					@if (ViewBag.ResultMsg != null && ViewBag.ResultMsg.Contains("thành công"))
					{
						<div class="alert alert-success" role="alert">
							@ViewBag.ResultMsg
						</div>
					}
					@if (ViewBag.ResultMsg != null && ViewBag.ResultMsg.Contains("thất bại"))
					{
						<div class="alert alert-danger" role="alert">
							@ViewBag.ResultMsg
						</div>
					}
				</div>
			</div>
			<div class="table-responsive">
				<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
					<thead>
						<tr>
							<th>Id</th>
							<th>Tên khách hàng giao</th>
							<th>Địa chỉ giao hàng</th>
							<th>Email giao hàng</th>
							<th>Số điện thoại</th>
							<th>Ngày tạo</th>
							<th>Trạng thái</th>
							<th>Tổng thanh toán</th>
							<th>Thao tác</th>
						</tr>
					</thead>
					<tbody>
						@foreach (var item in Model.Items)
						{
							<tr>
								<td>
									@Html.DisplayFor(modelItem => item.Id)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.ShipName)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.ShipAddress)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.ShipEmail)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.ShipPhoneNumber)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.OrderDate)
								</td>
								<td>
									<form id="update-OrderStatus" asp-action="UpdateStatus" asp-controller="Order" method="post">
										<input type="hidden" name="orderId" value="@item.Id"> 
										<select name="status">
											@if (item.Status == 0)
											{
												<option value="0">
													InProgress
												</option>
											}
											else if (item.Status == 1)
											{
												<option value="1">
													Confirmed
												</option>
											}
											else if (item.Status == 2)
											{
												<option value="2">
													Shipping
												</option>
											}
											else if (item.Status == 3)
											{
												<option  value="3">
													Success
												</option>
											}
											else
											{
												<option value="4">
													Canceled
												</option>
											}
											<option value="0">InProgress</option>
											<option value="1">Confirmed</option>
											<option value="2">Shipping</option>
											<option  value="3">Success</option>
											<option value="4">Canceled</option>
										</select>
									</form>
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Total)
								</td>
								<td>
									<button class="btn btn-btn-info" type="submit" form="update-OrderStatus" >Update Status</button>
								</td>
								<td>
								</td>
							</tr>
						}
					</tbody>
				</table>
			</div>
			@await Component.InvokeAsync("Pager", Model)
		</div>
	</div>

</div>
<!-- /.container-fluid -->
<!-- End of Main Content -->